export const SET_STATE_VIEW_CARD = 'SET_STATE_VIEW_CARD';
export const SET_STEP_BUILD_PC = 'SET_STEP_BUILD_PC';
export const GET_ALL_COMPONENTS = 'GET_ALL_COMPONENTS';
export const SET_NUM_PAGINATED = 'SET_NUM_PAGINATED';
export const SEARCH_COMPONENT = 'SEARCH_COMPONENT';
export const ORDER_PRICE = "ORDER_PRICE";
export const GET_DETAIL_COMPONENT = "GET_DETAIL_COMPONENT";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const DELETE_FILTER_CATEGORY = "DELETE_FILTER_CATEGORY";
export const PICK_ARMA_TU_PC = "PICK_ARMA_TU_PC";
export const CLEAN_ARMA_TU_PC = "CLEAN_ARMA_TU_PC"
export const EDIT_USER = "EDIT_USER"
//Shopping cart
export const ADD_TO_CART = "ADD_TO_CART"
export const INCREMENT_CART = "INCREMENT_CART"
export const DECREMENT_CART = "DECREMENT_CART"
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART"
