export const SET_STATE_VIEW_CARD = 'SET_STATE_VIEW_CARD';
export const SET_STEP_BUILD_PC = 'SET_STEP_BUILD_PC';
export const GET_ALL_COMPONENTS = 'GET_ALL_COMPONENTS';
export const SET_NUM_PAGINATED = 'SET_NUM_PAGINATED';
export const SEARCH_COMPONENT = 'SEARCH_COMPONENT';
